---
kind: pipeline
type: docker
name: Alfred host build
platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: ros:humble-ros-base-jammy
  commands:
    - cd workspace
    - rm -fR sim/
    - . /opt/ros/$ROS_DISTRO/setup.sh
    - apt-get update 
    - rosdep install -y
      --from-paths src/
      --ignore-src
      --skip-keys "console_bridge
        fastcdr
        fastrtps
        libopensplice67
        libopensplice69
        rti-connext-dds-5.3.1
        urdfdom_headers" 
    - rm -rf /var/lib/apt/lists/*
    - colcon build
      --symlink-install
      --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSYNTHETIC_BUILD:BOOL=ON
      --no-warn-unused-cli

- name: Build logs upload
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_build/(*)/(*)
    target: Alfred/logs/build/host/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
  depends_on:
    - Build

- name: Tests
  image: ros:humble-ros-base-jammy
  commands:
    - cd workspace
    - colcon test
    - colcon test-result
  when:
    status:
    - success
  depends_on:
    - Build

- name: Test logs upload
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_test/(*)/(*)
    target: Alfred/logs/tests/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
    - success
  depends_on:
    - Tests

---
kind: pipeline
type: docker
name: Alfred target build
platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: arm64v8/ubuntu:jammy
  environment:
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
    ROS_DISTRO: humble
#   commands:
#     - echo 'Etc/UTC' > /etc/timezone
#     - ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime
#     - apt-get update
#     - apt-get install -q -y --no-install-recommends tzdata dirmngr gnupg2
#     - rm -rf /var/lib/apt/lists/*
#     - echo "deb http://packages.ros.org/ros2/ubuntu jammy main" > /etc/apt/sources.list.d/ros2-latest.list
#     - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
#     - apt-get update && apt-get install --no-install-recommends -y
#         build-essential
#         python3-colcon-common-extensions
#         python3-colcon-mixin
#         python3-rosdep
#         python3-vcstool
#     - rm -rf /var/lib/apt/lists/*
#     - rosdep init
#     - rosdep update --rosdistro $ROS_DISTRO
#     - apt-get update && apt-get install -y --no-install-recommends ros-humble-ros-base=0.10.0-1*
#     - rm -rf /var/lib/apt/lists/*
#     - cd workspace
#     - rm -fR sim/
#     - . /opt/ros/$ROS_DISTRO/setup.sh
#     - apt-get update 
#     - rosdep install -y
#       --from-paths src/
#       --ignore-src
#       --skip-keys "console_bridge
#         fastcdr
#         fastrtps
#         libopensplice67
#         libopensplice69
#         rti-connext-dds-5.3.1
#         urdfdom_headers" 
#     - rm -rf /var/lib/apt/lists/*
#     - colcon build
#       --symlink-install
#       --cmake-args
#       --no-warn-unused-cli

- name: Logs upload
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_build/(*)/(*)
    target: Alfred/logs/build/target/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
  depends_on:
    - build

- name: Binaries upload
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/install/(*)
    target: Alfred/binaries/"$(date +'%Y-%m-%d_%H-%M')"/{1}
    flat: true
    insecure: true
  when:
    status:
    - success
  depends_on:
    - build


