---
kind: pipeline
type: docker
name: Alfred host build
platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: ros:humble-ros-base-jammy
  commands:
    - cd workspace
    - rm -fR sim/
    - . /opt/ros/$ROS_DISTRO/setup.sh
    - apt-get update 
    - rosdep install -y
      --from-paths src
      --ignore-src
      --skip-keys "fastcdr \
        rti-connext-dds-6.0.1 \
        urdfdom_headers"
    - rm -rf /var/lib/apt/lists/*
    - colcon build
      --symlink-install
      --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSYNTHETIC_BUILD:BOOL=ON
      --no-warn-unused-cli

- name: Upload build logs
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_build/(*)/(*)
    target: Alfred/logs/build/host/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
  depends_on:
    - Build

- name: Tests
  image: ros:humble-ros-base-jammy
  commands:
    - cd workspace
    - . /opt/ros/$ROS_DISTRO/setup.sh
    - apt-get update 
    - rosdep install -y
      --from-paths src
      --ignore-src
      --skip-keys "fastcdr \
        rti-connext-dds-6.0.1 \
        urdfdom_headers"
    - rm -rf /var/lib/apt/lists/*
    - colcon test
    - colcon test-result
  when:
    status:
    - success
  depends_on:
    - Build

- name: Upload test logs
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_test/(*)/(*)
    target: Alfred/logs/tests/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
    - success
  depends_on:
    - Tests

---
kind: pipeline
type: docker
name: Alfred target build
platform:
  os: linux
  arch: amd64

steps:
- name: Build
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
    - sleep 5 # give docker enough time to start
    - cd workspace/cross_compile
    - mkdir workspace
    - cp -r ../src workspace
    - rm -fR workspace/src/sim/
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker build -t arm_ros2:humble -f ./Dockerfile/Dockerfile_arm64_humble .
    - docker run --name alfred_cross arm_ros2:humble
    - docker cp alfred_cross:/ros2_ws/build/. ../build
    - docker cp alfred_cross:/ros2_ws/install/. ../install
    - docker cp alfred_cross:/ros2_ws/log/. ../log
    - rm -r workspace

- name: Upload build logs
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/log/latest_build/(*)/(*)
    target: Alfred/logs/build/target/"$(date +'%Y-%m-%d_%H-%M')"/{1}/{2}
    flat: true
    insecure: true
  when:
    status:
    - failure
  depends_on:
    - Build

- name: Upload binaries
  image: plugins/artifactory
  settings:
    url: http://192.168.1.252/artifactory
    username:
      from_secret: ARTIFACTORY_USERNAME
    password:
      from_secret: ARTIFACTORY_PASSWORD
    source: workspace/install/(*)
    target: Alfred/binaries/"$(date +'%Y-%m-%d_%H-%M')"/{1}
    flat: true
    insecure: true
  when:
    status:
    - success
  depends_on:
    - Build

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
