#ifndef HAL_MOTORCONTROL_COMMONDEFINITIONS
#define HAL_MOTORCONTROL_COMMONDEFINITIONS

#define MOTOR_LEFT_PWM_A_GPIO 9
#define MOTOR_LEFT_PWM_B_GPIO 25
#define MOTOR_LEFT_ENCODER_CH_A_GPIO 17
#define MOTOR_LEFT_ENCODER_CH_B_GPIO 18

#define MOTOR_RIGHT_PWM_A_GPIO 11
#define MOTOR_RIGHT_PWM_B_GPIO 8
#define MOTOR_RIGHT_ENCODER_CH_A_GPIO 22
#define MOTOR_RIGHT_ENCODER_CH_B_GPIO 23

#define AS_RISING_EDGE 0
#define AS_FALLING_EDGE 1
#define AS_EITHER_EDGE 2

#define FALLING_EDGE 0
#define RISING_EDGE 1
#define NO_CHANGE 2

#endif