FROM --platform=arm64 ros:humble-ros-base-jammy

COPY ./workspace/src /ros2_ws/src

WORKDIR /ros2_ws

RUN apt-get update && rosdep install -y \
    --rosdistro humble \
    --from-paths src \
    --ignore-src \
    --skip-keys "fastcdr \
        rti-connext-dds-6.0.1 \
        urdfdom_headers"

RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build \
        --symlink-install \
        --cmake-args --no-warn-unused-cli

RUN tar -h -czvf install.tar.gz install
