FROM --platform=arm64 ros:humble-ros-base-jammy

COPY ./workspace/src /ros2_ws/src

WORKDIR /ros2_ws

RUN apt-get update && rosdep install -y \
    --rosdistro humble \
    --from-paths src \
    --ignore-src \
    --skip-keys "fastcdr \
        rti-connext-dds-6.0.1 \
        urdfdom_headers"

WORKDIR /   
RUN apt-get update && apt-get install -y symlinks
RUN symlinks -rc .
